"""Teaching-oriented nonlinear dynamic inversion controller.

The controller uses the simplified longitudinal model to invert two channels:

* speed rate -> throttle command;
* pitch-rate acceleration -> elevator command.

It is intentionally partial NDI. The altitude/gamma/alpha commands are still
generated by simple outer-loop logic so readers can see where dynamic inversion
helps and where a full backstepping or constrained design is still needed.
"""

from __future__ import annotations

from dataclasses import dataclass
import math

from hgv_control.models.longitudinal import (
    LongitudinalParams,
    State,
    aero_forces,
    clamp,
    derivatives,
    dynamic_pressure,
)


@dataclass
class NdiController:
    h_gain: float = 3.0e-4
    gamma_gain: float = 2.5
    alpha_gain: float = 3.0
    q_gain: float = 8.0
    v_gain: float = 0.045
    trim_throttle: float = 0.62
    alpha_trim: float = math.radians(2.0)

    def _throttle_command(
        self,
        state: State,
        velocity_ref: float,
        params: LongitudinalParams,
    ) -> float:
        _, drag, _, _ = aero_forces(state, self.trim_throttle, params)
        vdot_cmd = clamp(self.v_gain * (velocity_ref - state.velocity), -7.0, 7.0)
        thrust_required = params.mass * (vdot_cmd + params.gravity * math.sin(state.gamma)) + drag
        denom = params.thrust_max * max(0.2, math.cos(state.alpha))
        return clamp(thrust_required / denom, params.throttle_min, params.throttle_max)

    def _elevator_command(
        self,
        state: State,
        altitude_ref: float,
        throttle_cmd: float,
        params: LongitudinalParams,
    ) -> float:
        gamma_cmd = clamp(self.h_gain * (altitude_ref - state.altitude), math.radians(-7.0), math.radians(7.0))
        alpha_cmd = self.alpha_trim + clamp(
            self.gamma_gain * (gamma_cmd - state.gamma),
            math.radians(-4.5),
            math.radians(4.5),
        )
        alpha_cmd = clamp(alpha_cmd, math.radians(-6.0), math.radians(10.0))

        gamma_dot = derivatives(state, state.elevator, throttle_cmd, params).gamma
        q_cmd = gamma_dot + self.alpha_gain * (alpha_cmd - state.alpha)
        q_cmd = clamp(q_cmd, math.radians(-20.0), math.radians(20.0))
        qdot_cmd = clamp(self.q_gain * (q_cmd - state.pitch_rate), math.radians(-70.0), math.radians(70.0))

        qbar = max(1.0, dynamic_pressure(state, params))
        velocity = max(100.0, state.velocity)
        moment_scale = qbar * params.ref_area * params.ref_chord / params.iy
        a_q = moment_scale * (
            params.cm_alpha * state.alpha
            + params.cm_q * (params.ref_chord / (2.0 * velocity)) * state.pitch_rate
        )
        b_q = moment_scale * params.cm_delta
        if abs(b_q) < 1e-6:
            return clamp(state.elevator, -params.delta_limit, params.delta_limit)

        delta_cmd = (qdot_cmd - a_q) / b_q
        return clamp(delta_cmd, -params.delta_limit, params.delta_limit)

    def command(
        self,
        state: State,
        altitude_ref: float,
        velocity_ref: float,
        params: LongitudinalParams,
    ) -> tuple[float, float]:
        throttle_cmd = self._throttle_command(state, velocity_ref, params)
        delta_cmd = self._elevator_command(state, altitude_ref, throttle_cmd, params)
        return delta_cmd, throttle_cmd
